### ISSUE TITLE
Fedora 25 mimic compile errors

### ISSUE THREAD

**Issue by jlapthorn** [MycroftAI/mimic#102]
Problem installing from git on Fedora 25, build_host_setup_fedora.sh completes without errors.  ./dev_setup.sh fails when compiling mimic

checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/james/mycroft-core/mimic':
configure: error: C compiler cannot create executables

config.log says error 77

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "mimic"
#define PACKAGE_TARNAME "mimic"
#define PACKAGE_VERSION "1.2.0.1"
#define PACKAGE_STRING "mimic 1.2.0.1"
#define PACKAGE_BUGREPORT "https://github.com/MycroftAI/mimic/issues"
#define PACKAGE_URL ""
#define PACKAGE "mimic"
#define VERSION "1.2.0.1"

configure: exit 77

Any help would be appreciated :-)

**Comment by forslund** [comment]
Have you run the `build_host_setup_fedora.sh` script so the prerequisites are installed. (might need a couple of more packages nowadays: `libicu-devel` and `pkgconfig`, `gcc`, `automake` I think. I'm not a fedora user)

From the little I can see there seems to be some problem with the gcc installation. Make sure that it's properly installed. Can you post your entire config.log on pastbin or as a gist?

**Comment by jlapthorn** [comment]
I have run the build_host_setup_fedora.sh.    I'll try again with the additional packages you suggested.  

Here's a copy of my config.log

https://gist.github.com/jlapthorn/58079ce6b974e461b9859e46bc0d9eb6#file-gistfile1-txt

**Comment by jlapthorn** [comment]
Adding the additional package libicu-devel resolved the compile errors. Probably worth adding this to the build_host_setup_fedora.sh script :-) Thanks for your help

**Comment by zeehio** [comment]
I'm on it

**Comment by zeehio** [comment]
This is `mycroft-core` related, so it is be addressed at https://github.com/MycroftAI/mycroft-core/issues/568 and https://github.com/MycroftAI/mycroft-core/issues/573

I close this issue since we already describe our dependencies in the `README.md` and with those dependencies mimic can be built.

Thanks for reporting :+1:
