### ISSUE TITLE
Proposal: change default branch to "development"

### ISSUE THREAD

**Issue by zeehio** [MycroftAI/mimic#106]
Github allows to set the default branch where pull requests should go, I believe we should set it to "development" instead of "master", if we want new PR to go to "development" by default.

The preference can be changed in https://github.com/MycroftAI/mimic/settings/branches

**Comment by forslund** [comment]
Agreed, I've thought of changing it myself but have been putting it off. I say go ahead and do it.

**Comment by zeehio** [comment]
I don't have the permissions 😅

**Comment by forslund** [comment]
I'll see if I can do it then =)

Den 20 mar 2017 5:45 em skrev "Sergio Oller" <notifications@github.com>:

**Comment by forslund** [comment]
I don't seem to have permission either. Maybe @aatchison or @agustnmonteiro could do it?

**Comment by zeehio** [comment]
We have already received three redundant pull requests to fix the readme formatting because master is the default branch instead of development.

**Comment by forslund** [comment]
Default branch is now *development*. Closing =)
