### ISSUE TITLE
Use python included uuid rather than third party

### ISSUE THREAD

**Issue by nullr0ute** [MycroftAI/mimic#113]
Git commit cd1a36b added uuid (https://pypi.python.org/pypi/uuid/1.30) as a dependency that doesn't support python3 and is unmaintained (last release was 2007). The python standard library already includes a rfc4122 generator so that should be used instead (https://docs.python.org/2/library/uuid.html).

**Comment by penrods** [comment]
Did you intend to file this issue on mycroft-core?

**Comment by nullr0ute** [comment]
Yes, clearly I should wait for caffeine to kick in before doing stuff :-/

**Comment by penrods** [comment]
Ha!  No worry, but do you mind closing this one and reopening over there.  I'll look in to it once I've had the appropriate amount of caffeine.  :)

**Comment by penrods** [comment]
See what I mean...you already did it.  I need to go to bed.
