### ISSUE TITLE
Why does build take so long on Linux?

### ISSUE THREAD

**Issue by zacharisharris** [MycroftAI/mimic#116]
I am in the build process (make) and it seems to take too long. It is stuck on a line that reads:
  CC       lang/vid_gb_ap/libttsmimic_lang_vid_gb_ap_la-vid_gb_ap_cg_01_mcep_trees.lo

What is wrong? Is it an error? Should I wait?
I am running it on GalliumOS on an Acer Chromebook 14.

**Comment by forslund** [comment]
Hi @zacharisharris building that voice takes a _really_ long time I'm afraid. The size of the data that needs to be compiled into the binary for that voice is extraordinary large. Be patient and have a cup of tea.

If your computer has multiple cores you can try to build using `make -jCORES` where CORES is the number of cores available on your computer. This will consume a lot more memory during build time and gcc may crash if it runs out.

**Comment by zacharisharris** [comment]
I have it running right now. What is the ETA? Will it take days or maybe just tonight?

**Comment by forslund** [comment]
Just tonight =/

My workstation at home is an AMD machine which takes ~2 Hours to build it, my laptop is an Intel i3 and builds mimic in ~30 minutes.

I would guess no longer than 2 hours.

**Comment by zacharisharris** [comment]
Nice. I am running it on my Linux laptop, but ultimately I wanna run it on RPi 2 to power my personal voice assistant. Is it good for personal use?

**Comment by forslund** [comment]
I've not tried it on an RPi2 on a RPi3 it's no problems though.

**Comment by zacharisharris** [comment]
Will it work with my Python voice assistant instead of espeak?

**Comment by forslund** [comment]
Not sure. I've been working on pymimic a python wrapper for mimic: https://github.com/forslund/pymimic is that what you're asking for? Mycroft wraps the command line application using `subprocess.Popen()`

**Comment by zacharisharris** [comment]
My assistant runs the command line commands for espeak when replying to the user. Mimic has command line commands as well, correct? I don't see why it wouldn't work.

**Comment by forslund** [comment]
Yes that is correct, there should be no problems

**Comment by forslund** [comment]
Did you run `make install` as root/su?

Den 4 maj 2017 11:43 em skrev "Harris Zacharis" <notifications@github.com>:

**Comment by zacharisharris** [comment]
No. Simple make install

**Comment by zacharisharris** [comment]
I just copied the mimic-development folder to my home folder so now I just have to run the .mimic command. Is that correct?

**Comment by forslund** [comment]
Yeah launching the mimic command from your home dir should be no different
from your download dir.

(If you mean something like ./mimic -t "hello there")

Den 4 maj 2017 11:49 em skrev "Harris Zacharis" <notifications@github.com>:

**Comment by zacharisharris** [comment]
Hey please send me a personal email on zacharisharris@gmail.com so that we can talk in private.
