### ISSUE TITLE
Consider switching ICU to pcre

### ISSUE THREAD

**Issue by zeehio** [MycroftAI/mimic#120]
[pcre2](http://www.pcre.org) has a smaller scope (just regular expressions) and supports UTF-8. It is easier and faster to build than ICU and as it is a C library we would not need a C++ compiler, for instance on cross-compilation.

Not only that, but also given its size we can consider embedding a copy of the pcre library in mimic and, in case the library is not found, compile it.

`pcre` is used by nginx, julia and R among other projects, so it is quite popular

This is on my to-do list after I finish the thesis, feel free to work on it if you want

**Comment by forslund** [comment]
Sounds like a good idea. I'll put it on my todo list for next week.

**Comment by zeehio** [comment]
I will get on to this now if you have not started yet 👍

**Comment by forslund** [comment]
Go right ahead!

Den 10 juni 2017 17:02 skrev "Sergio Oller" <notifications@github.com>:

**Comment by zeehio** [comment]
Closed by #121
