### ISSUE TITLE
Sound output on Mac OS X

### ISSUE THREAD

**Issue by forslund** [MycroftAI/mimic#13]
The engine works on Mac OS X but cannot generate sound output (only file output is possible). Many users would be grateful if also the Mac could speak.

**Comment by zeehio** [comment]
I will send a patch in 5 hours with Mac OS X support via the PortAudio library. Would you be able to test it?

**Comment by siavasht** [comment]
I will be able to test the patch if you send it before midnight (CET)

**Comment by zeehio** [comment]
I was too late for you @siavasht. Will you be able to test it another day? :sweat_smile: 

Thanks!

**Comment by siavasht** [comment]
It might be in a couple of days but I will test again as soon as I can get my hands on a Macbook :smile:

**Comment by Dabuk** [comment]
Hey, I tried this, the problem seems to persist. Is any extra command line arguement necessary?
Also the libasound2-dev is not installed on my mac. Is it necessary?

**Comment by forslund** [comment]
You'll need [portaudio](http://portaudio.com). If you can't get it from homebrew there are instructions for build instructions [here](http://portaudio.com/docs/v19-doxydocs/compile_mac_coreaudio.html)

**Comment by forslund** [comment]
If it still doesn't work can you see if you can provide the full path to ```portaudio.h```?

**Comment by zeehio** [comment]
In order to force the use of the portaudio module, use:

    ./configure --with-audio=portaudio
    make

You will need the portaudio library, that can be installed using brew:

# Install brew:

    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install portaudio (requires brew):

    brew install portaudio

**Comment by zeehio** [comment]
Mac OS X now has audio support through PortAudio. The README.md has updated instructions on how to build it and install it. Merged in #14
