### ISSUE TITLE
Specify pronunciation for some words

### ISSUE THREAD

**Issue by rinigus** [MycroftAI/mimic#133]
I am using mimic for voice prompts in navigation software (runs on a mobile Linux for phones). It works very well, thank you very much!

The navigation routing engine (Valhalla), in addition to regular English, has a pirate version of the instructions. In general, mimic does a good job, but gets into trouble with pronouncing `Arrr`, `th'`, `Cap'n wheel` and probably few others.

I wonder, if its possible to feed mimic pronunciation of such special words as a part of an input string?

**Comment by forslund** [comment]
Hi. You can use the ssml markup langauge to do things like this:

```
./mimic -ssml -t 'You say <phoneme ph="t ax m ey1 t ow">tomato </phoneme> while I say <phoneme ph="t ax m ae1 t ow">tomato</phoneme>.'
```

It's a bit tricky to get the correct pronounciation of Arrr and a lot of experimentation may be needed.

You can use http://www.speech.cs.cmu.edu/cgi-bin/cmudict to get some guidance

**Comment by rinigus** [comment]
Thank you very much, that's exactly what I was missing! Closing the issue
