### ISSUE TITLE
clunits: can't find tree for pau_ax

### ISSUE THREAD

**Issue by zangetsudo** [MycroftAI/mimic#144]
sorry, guys, me again
i want to write all the voices done showing in the Usage as you suggested in the last post.

if i try with the words from the Usage list, it's ok.
`#for i in ap slt slt_hts kal awb kal16 rms awb_time; do ./mimic -t "Hello. Doctor. Name. Continue. Yesterday. Tomorrow." -voice $i -o ./voice/$i.wav;done`

but others failed to process.
```
# for i in ap slt slt_hts kal awb kal16 rms awb_time; do ./mimic -t "A large percentage of classpath related problems are caused by using one word in the source code and a slightly different spelling or abbreviation of that word in the filesystem" -voice $i -o ./voice/$i.wav;done
```
that's the output:
```
clunits: can't find tree for pau_ax
clunit_get_unit_index: can't find unit type pau_ax, using 0
clunit_get_unit_index: can't find unit type pau_ax, using 0
clunit_get_unit_index: can't find unit type pau_ax, using 0
clunit_get_unit_index: can't find unit type pau_ax, using 0
clunit_get_unit_index: can't find unit type pau_ax, using 0
clunit_get_unit_index: can't find unit type pau_ax, using 0
clunit_get_unit_index: can't find unit type pau_ax, using 0
clunit_get_unit_index: can't find unit type pau_ax, using 0
clunit_get_unit_index: can't find unit type pau_ax, using 0
clunit_get_unit_index: can't find unit type pau_ax, using 0
clunit_get_unit_index: can't find unit type pau_ax, using 0
clunit_get_unit_index: can't find unit type pau_ax, using 0
```

is it an issue?

**Comment by zangetsudo** [comment]
i found out the words "in the source code" is a kind of related
it works with out that words, or "in source code".

**Comment by zeehio** [comment]
Thanks for the report.

This happens with the `awb_time` voice, that was built with a limited domain approach, just to be able to say the time of the day. The `awb_time` voice should not be used for other purposes.

I close this issue, as it will be documented at https://github.com/MycroftAI/mimic-cmu_time_awb/issues/1
