### ISSUE TITLE
Lexicon conflicts

### ISSUE THREAD

**Issue by piretro999** [MycroftAI/mimic#146]
I noticed that a lot of skills share the same words to operate.
This is normal due to the fact that they do similar things or the same word can be applied to different task.
and here is the problem. How can mycroft understand what to do if I say "play gun's and roses" and has two or more skills that uses that sintax? In this case, as an example I recieve an answer "You are currently not subscribed to that station" maybe because I  have installed a radio module and Mopidy.
Now how to make sure that the machine does the right thing?
I see many ways, like having a centralized resource that assign phrases to single skills or to modifiable hierarchies. or having an answer from Mycroft that ask for what skill use for that task.
However, in general, a centralized database for words, phrases and regular expressions could help alot to more task, like extending to other languages.

**Comment by forslund** [comment]
Hi @pietro999, could you move this issue to the mycroft-core repository? It's more of a mycroft thing than a mimic (Text to speech) thing.

Secondly, this is an issue we are (slowly) working on.

We have an idea that the intent handler will call all matching skills and query if it can handle the request. The skills return a confidence and the intent handler selects the one with the highest confidence. Also lots of tiny details when two or more skills can handle an utterance with similar confidence. (like the clarification query from Mycroft you suggest)

Love to hear more of your ideas regarding this!

**Comment by forslund** [comment]
I'm closing this since it's related to Mycroft and not Mimic.
