### ISSUE TITLE
Test - 8 Passed, 1 failed

### ISSUE THREAD

**Issue by smithaitufe** [MycroftAI/mimic#147]
Hi, I just installed mimic in my Ubuntu 16.10.
I followed the installation instructions and everything was fine.
Then I ran make test, I got this response

```cmd
PASS: unittests/hrg_test
PASS: unittests/regex_test
FAIL: unittests/string_test
PASS: unittests/token_test
PASS: unittests/voice_select
PASS: unittests/wave_test
PASS: unittests/lex_test
PASS: unittests/lts_test
PASS: unittests/nums_test
============================================================================
Testsuite summary for mimic 1.1.0.9000
============================================================================
# TOTAL: 9
# PASS:  8
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to https://github.com/MycroftAI/mimic/issues
============================================================================
Makefile:4695: recipe for target 'test-suite.log' failed
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory '/home/smith/mimic'
Makefile:4801: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory '/home/smith/mimic'
Makefile:5095: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/smith/mimic'
Makefile:4581: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```

After the above, I ran `mimic --help` and I was told that mimic is not a command

What does this mean

**Comment by el-tocino** [comment]
The not a command bit means that mimic is not found in the current path. 

Did you install all of the prerequisites? Any warnings when configuring and making?

**Comment by smithaitufe** [comment]
First, I simply followed the instructions for installation which means that I installed on the dependencies.

Second, out of 9 tests, 8 passed. Should that disturb me?

Thirdly, do I have to manually make the command available globally by adding it to PATH?

**Comment by forslund** [comment]
Hi @smithaitufe, the error is likely due to some language/encoding issues we've recently backported some fixes for this (merged a minute ago) so you might want to 

You can run `sudo make install` to install mimic to `usr/local/bin` which is in the standard path

**Comment by smithaitufe** [comment]
@forslund are you suggesting that I should go over the circle again?

**Comment by zeehio** [comment]
You can use `git pull` from the directory, and then make again. Only the things that have changed will be rebuilt

**Comment by smithaitufe** [comment]
@zeehio Thanks a lot. Well, I just tried the one I cloned before using `sudo make install` and it worked. I think the reason why it was reporting that mimic is not a command was because I missed `sudo`. I will close this for now.
