### ISSUE TITLE
Configure fails on Fedora

### ISSUE THREAD

**Issue by ghost** [MycroftAI/mimic#196]
Running configure scripts fails on Fedora 31:
```
configure: creating ./config.status
config.status: creating Makefile
config.status: creating mimic.pc
config.status: creating include/config.h
config.status: executing depfiles commands
config.status: error: in `/home/default/Development/mycroft-core/mimic1':
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details
```
The same error occurs both on master and development branches. The script indeed succeeds if `--disable-dependency-tracking` is set but I guess it should not be done since mycroft-core doesn't set it either.

Here's [config.log](https://gist.github.com/countcretinos/356b578d7fca759719652acdfac55e9f).

**Comment by forslund** [comment]
Hi skimmed through the config.log and the big issue seems to be it not finding the `make` command. Not sure which package contains make (mycroft-core's dev-setup installs the automake package which I would have assumed contained make)

**Comment by forslund** [comment]
Since you seem to have found the issue in the Mycroft-core dev-setup.sh I'm closing this Issue.
