### ISSUE TITLE
Test failure on the s390x architecture

### ISSUE THREAD

**Issue by PureTryOut** [MycroftAI/mimic#198]
I'm running the mimic1 tests on Alpine Linux. The tests succeed on all arches _but_ s390x.

Sadly the tests don't log to stderr and only to a log file, but since it's run on a CI job I can't easily get access to it.

```
PASS: unittests/hrg_test
PASS: unittests/string_test
FAIL: unittests/token_test
FAIL: unittests/lex_test
PASS: unittests/regex_test
FAIL: unittests/nums_test
FAIL: unittests/lts_test
FAIL: unittests/wave_test
FAIL: unittests/voice_select
make[3]: *** [Makefile:4921: test-suite.log] Error 1
make[2]: *** [Makefile:5029: check-TESTS] Error 2
make[1]: *** [Makefile:5330: check-am] Error 2
============================================================================
Testsuite summary for mimic 1.3.0.1
============================================================================
# TOTAL: 9
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  6
# XPASS: 0
# ERROR: 0
```

I however doubt you guys support mimic1 on s390x and if so, I'd like a statement here that it isn't supported in which case I'll just disable the arch entirely for the Alpine packaging.

**Comment by forslund** [comment]
It's not an architecture I have access to so the Mycroft team will not support it for now.

**Comment by PureTryOut** [comment]
Thanks, that's good enough for me!
