### ISSUE TITLE
Fulls top or space is not detecting.

### ISSUE THREAD

**Issue by shyam3089** [MycroftAI/mimic#201]
I'm trying to add silence after each sentence.
Adding full stop or multiple spaces are not working.
`./mimic ./mimic1/doc/alice -t "Hello there. I am Robo" -voice /home/pi/mimic1/voices/cmu_us_bdl.flitevox`

**Comment by sinsac** [comment]
Add return characters

**Comment by shyam3089** [comment]
Could please write an example?

**Comment by shyam3089** [comment]
Could please write an example?

**Comment by shyam3089** [comment]
Could please write an example?
