### ISSUE TITLE
Compilation fails: multiple definition of cst_rx_not_indic

### ISSUE THREAD

**Issue by kauron** [MycroftAI/mimic#202]
I'm trying to compile version 1.3.0.1, using the following commands:
```
./autogen.sh
./configure --prefix=/usr
make
```
this process fails with the following error:
```
/usr/bin/ld: REDACTED/mimic1-1.3.0.1/.libs/libttsmimic_lang_cmu_indic_lex.a(cmu_indic_lex.o):(.rodata+0x880): multiple definition of `cst_rx_not_indic'; ./.libs/libttsmimic_lang_all_langs.a(mimic_lang_list.o):(.rodata+0x0): first defined here
/usr/bin/ld: REDACTED/mimic1-1.3.0.1/.libs/libttsmimic_lang_cmu_indic_lang.a(cmu_indic_lang.o):(.data.rel.ro.local+0x40): multiple definition of `cst_rx_not_indic'; ./.libs/libttsmimic_lang_all_langs.a(mimic_lang_list.o):(.rodata+0x0): first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:3003: mimic] Error 1
make[1]: Leaving directory 'REDACTED//mimic1-1.3.0.1'
make: *** [Makefile:4805: all-recursive] Error 1
```

Software versions:
* ld: 2.34.0 (GNU)
* gcc: 10.1.0

The same error occurs when building against `master`.

**Comment by forslund** [comment]
Hi,  those are very recent versions compared to mine :)

I can't reproduce on
- ld (GNU Binutils for Ubuntu) 2.30
- gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

Gonna see if I can get a more modern setup going.

**Comment by kauron** [comment]
The issue still happens when compiling with gcc 8.4.0, by setting `alias gcc gcc-8` before starting the process

**Comment by forslund** [comment]
That's weird I have built mimic with gcc 9.3.x before...

**Comment by kauron** [comment]
If you want to reproduce the issue, I found that it occurs in the docker image for `archlinux:latest`, so if you start a container with `docker run -it archlinux`, you can compile and see the error:
```
pacman -Sy
pacman -S --needed git pcre2 gcc make pkg-config automake libtool alsa-lib m4 autoconf
git clone https://github.com/MycroftAI/mimic1.git
# optional
# git checkout 1.3.0.1
./autogen.sh
./configure
make
```
I also tried to repro the issue in the `ubuntu:20.04` image, but I couldn't (everything worked just fine).

PS: the default mirror for the archlinux's docker image is a bit slow, so as a solution, select a more appropriate mirror from [here](https://www.archlinux.org/mirrors/status/) and select it with
```
echo "Server = server_with_escaped_\$dollars" > /etc/pacman.d/mirrorlist
```

**Comment by forslund** [comment]
Thanks, will give it a go

**Comment by landorg** [comment]
> Adding `--disable-lang-indic` to the ./configure command made it work.

[credits](https://github.com/MycroftAI/mimic1/issues/205#issuecomment-636600155)

**Comment by cargaji** [comment]
That got it working, thank you.

**Comment by kauron** [comment]
That got it working, thank you!

**Comment by detrout** [comment]
Just to add a bit more information, I tried building on Debian unstable with gcc 10.2.1 and got this error. (Through ccache).
Outside of the builder on my testing system with gcc 9.3.0 it builds fine. The ```--disable-lang-indic``` work-around worked

**Comment by forslund** [comment]
@detrout there is a solution in pr #211, we're waiting for a CLA before being able to merge :/
