### ISSUE TITLE
Is there anyway to run programmatically without using terminal command?

### ISSUE THREAD

**Issue by shyam3089** [MycroftAI/mimic#204]
I'm using this way to run mimic in a python script. Is there any other simple way to say text?

```
cmd_beg= '/home/pi/mimic1/mimic --setf duration_stretch=0.9 --setf f0_shift=1 --setf int_f0_target_mean=110 -pw /home/pi/mimic1/doc/alice -t '
cmd_end= ' -voice /home/pi/mimic1/voices/cmu_us_awb.flitevox'
text = '"Booting complete"'
call([cmd_beg+text+cmd_end], shell=True)
```

**Comment by forslund** [comment]
You can check out [pymimic](https://github.com/forslund/pymimic), python bindings for mimic, I haven't worked on it for a whilie though

**Comment by forslund** [comment]
Did that answer your question?

**Comment by shyam3089** [comment]
I have seen pymimic already. It's an image not a wrapper. Still using terminal commands.

**Comment by forslund** [comment]
pymimic uses the mimic libraries not the command-line. See [here](https://github.com/forslund/pymimic/blob/master/pymimic/pymimic.py)
