### ISSUE TITLE
Publish prebuilt mimic releases

### ISSUE THREAD

**Issue by NoamDev** [MycroftAI/mimic#206]
Building mimic takes a lot of time.
Could you set up a CD that'll release zip files for linux, windows, etc. ?
I'm working on a porting Mycroft to windows (MycroftAI/mycroft-core#2627), but since mimic has to be cross-compiled from linux, it's not possible to build it during installation.

**Comment by forslund** [comment]
It can be built on windows using mingw but a precompiled zip is much more convenient. If I can't create a CI/CD pipeline I should be able to host a zipped windows package.

**Comment by forslund** [comment]
A prebuilt binary is now added to the latest release. Will keep them going for future updates.
