### ISSUE TITLE
windows cross-compilation instructions are not exact.

### ISSUE THREAD

**Issue by NoamDev** [MycroftAI/mimic#207]
Since ubuntu 17-18 at least, wine is a virtual package.
To install it, you need to type:
`apt-get install wine-stable`.
Does it happen in ubuntu 14/16 or is it something new? I ask because I want to send a pr to fix this in the readme.

**Comment by forslund** [comment]
Seems like it became a virtual package in 18.04. Would thankfully accept a Readme update

**Comment by NoamDev** [comment]
I did so
