### ISSUE TITLE
Linking fails, but easily fixed

### ISSUE THREAD

**Issue by MichaelSabal** [MycroftAI/mimic#214]
gcc 10.2.0:
Linking fails until an "extern" prefix is added to lang/cmu_indic_lang/cmu_indic_lang.h, line 54, for symbol cst_rx_not_indic.  All is well after the extern is added.

**Comment by forslund** [comment]
Hi thanks for this. Sounds like the same as #211 ? That PR has been stalled waiting for CLA signing, If you're willing to sign the cla at https://mycroft.ai/cla/, I'd be happy to merge a PR for this :)

**Comment by krisgesling** [comment]
CLA request received - a form is inbound. Thanks Michael!
