### ISSUE TITLE
mimic -p '' segs

### ISSUE THREAD

**Issue by penguin42** [MycroftAI/mimic#221]
**Describe the bug**
mimic -p ''   segfaults

**To Reproduce**
1. mimic -p ''

**Expected behavior**
Either an error, or silence

**Log files**

#0  0x000000000040e0b8 in get_dltmat (dno=1, dmat=0x646b470, dw=<synthetic pointer>, mat=0x646b800) at src/cg/cst_mlpg.c:333
        i = 0
        j = -1
        k = 0
        tmpnum = -1
        i = <optimized out>
        j = <optimized out>
        k = <optimized out>
        tmpnum = <optimized out>
#1  mlpg (param_track=param_track@entry=0x646b0b0, cg_db=cg_db@entry=0x163ca00 <vid_gb_ap_cg_db>) at src/cg/cst_mlpg.c:1027
        param = 0x646b140
        out = 0x646b110
        dim = 80
        dim_st = 40
        i = <optimized out>
        j = <optimized out>
        nframes = 0
        pst = {vSize = <optimized out>, order = <optimized out>, T = <optimized out>, width = <optimized out>, dw = {
            num = <optimized out>, width = <optimized out>, coef = <optimized out>, coef_ptrs = <optimized out>, maxw = {
              <optimized out>, <optimized out>}}, mseq = <optimized out>, ivseq = <optimized out>, ifvseq = <optimized out>, 
          R = <optimized out>, r = <optimized out>, g = <optimized out>, c = <optimized out>}
#2  0x000000000040be14 in cg_resynth (utt=0x6469de0) at src/cg/cst_cg.c:633
        cg_db = 0x163ca00 <vid_gb_ap_cg_db>
        w = <optimized out>
        param_track = 0x646b0b0
        str_track = 0x646b0e0
        asi = 0x0
        smoothed_track = <optimized out>
        streaming_info_val = <optimized out>
        cg_db = <optimized out>
        w = <optimized out>
        param_track = <optimized out>
        str_track = <optimized out>
        smoothed_track = <optimized out>
        streaming_info_val = <optimized out>
        asi = <optimized out>
#3  cg_synth (utt=0x6469de0) at src/cg/cst_cg.c:156
        cg_db = 0x163ca00 <vid_gb_ap_cg_db>
#4  0x0000000000426b72 in apply_synth_method (meth=0x644c7c0 <synth_method_phones+96>, u=<optimized out>, u@entry=0x6469de0)
    at src/synth/cst_synth.c:163
No locals.
#5  utt_synth_phones (u=u@entry=0x6469de0) at src/synth/cst_synth.c:202
No locals.
#6  0x0000000000427a29 in mimic_do_synth (synth=<optimized out>, voice=0x645c2d0, u=0x6469de0) at src/synth/mimic.c:195
No locals.
#7  mimic_synth_phones (voice=0x645c2d0, text=0x7fffffffe3a6 "") at src/synth/mimic.c:219
        u = 0x6469de0
        u = <optimized out>
#8  mimic_phones_to_speech (text=text@entry=0x7fffffffe3a6 "", voice=voice@entry=0x645c2d0, outtype=outtype@entry=0x43706f "play", 
    dur=dur@entry=0x7fffffffdefc) at src/synth/mimic.c:391
        u = <optimized out>
        ret = <optimized out>
#9  0x0000000000402ae9 in main (argc=<optimized out>, argv=<optimized out>) at main/mimic_main.c:424
        tv = {tv_sec = 1629595604, tv_usec = 150059}
        v = 0x645c2d0
        filename = 0x7fffffffe3a6 ""
        outtype = 0x43706f "play"
        desired_voice = 0x645c2d0
        voicedir = <optimized out>
        i = <optimized out>
        err = <optimized out>
        durs = 0
        time_start = 1629595604.150059
        time_end = <optimized out>
        mimic_verbose = <optimized out>
        mimic_loop = <optimized out>
        mimic_bench = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
        explicit_filename = <optimized out>
        explicit_text = 0
        explicit_phones = <optimized out>
        ssml_mode = <optimized out>
        bench_iter = 0
        extra_feats = 0x645c2a0
        lex_addenda_file = <optimized out>
        voicedumpfile = <optimized out>
        asi = <optimized out>

**Environment (please complete the following information):**
 - Device type: desktop x86
 - OS: Fedora 34
 - Other versions: Both current git head ( c2cbf31198 ) and Fedora's 1.3.0.1-5 mimic package

**Comment by forslund** [comment]
Thanks for reporting this issue. We should add a small validation function to verify this case and report the issue...maybe even some more validation could be added to make sure the phoneme string makes sense...
