### ISSUE TITLE
"Shared" compilation (with --enable-shared=yes) fails.

### ISSUE THREAD

**Issue by Achaean** [MycroftAI/mimic#234]
**Hi!**  :-)

(On a Debian stable based distribution), I ran the commands autogen, configure (with the option "--enable-shared=yes"), make, make check, make install (as root) and make installcheck, successfully.

Unfortunately, mimin can't run and complains for a missing lib, although it's actually there:

```
>mimic -h
mimic: error while loading shared libraries: libttsmimic_lang_all_langs.so.0: cannot open shared object file: No such file or directory
>
```

```
>locate libttsmimic_lang_all_langs.so.0
/usr/local/lib/libttsmimic_lang_all_langs.so.0
/usr/local/lib/libttsmimic_lang_all_langs.so.0.0.0
>
```

**PS.** Omitting the above argument (--enable-shared=yes), returns a static build, who is running perfectly.

**Comment by forslund** [comment]
Hi!

Did you try running `ldconfig` as root to rebuild the linkers cache? (Or reboot the machine)

I will try to replicate the issue tonight

**Comment by Achaean** [comment]
Ooops!!!  Mea culpa.
I totally forgot to ldconfig afterwards.

**SORRY!!!**  :-)
