### ISSUE TITLE
Kick Off a Release

### ISSUE THREAD

**Issue by ryanleesipes** [MycroftAI/mimic#40]
Current version works pretty damn good, and if we kick off a stable release (it seems stable right now). We can use that version for Mycroft.

**Comment by forslund** [comment]
I agree, I would like #37 to be included, we wouldn't want to break the build process in master. After that (or equivalent) is in development I think we could merge into master and create a release.

**Comment by LongBoolean** [comment]
@forslund you took the words right out of my mouth. @ryanleesipes Once the development branch is in a satisfactory state all that needs to happen is to merge development into master and tag that commit on master as a release. (The goal being to keep the master branch stable, and let the development branch be the place to screw things up and go wild.)

**Comment by forslund** [comment]
I've merged the "make clean fix". @LongBoolean could you handle the release procedure?

**Comment by LongBoolean** [comment]
sure, no problem.

**Comment by zeehio** [comment]
This was done some time ago already. Feel free to reopen if I am missing anything
