### ISSUE TITLE
Name clash: There is an unarelated shared library named "libmimic.so"

### ISSUE THREAD

**Issue by zeehio** [MycroftAI/mimic#63]
From synaptic, the package manager:

```
libmimic is an open source video decoding library for decoding Mimic V2.x-
encoded content (fourCC: ML20), which is the encoding used by MSN Messenger
for webcam conversations.
```
The codecs metapackage `mint-meta-codecs` on Linux Mint installs it, as a dependency of some of the gstreamer multimedia plugins.

I suggest renaming mimic libraries from libmimic to libttsmimic, any other ideas?

(I was going crazy until I found out I was not linking to the right library!)

**Comment by forslund** [comment]
Sounds ok to me. Maybe @aatchinson has an opinion, he's doing the packaging of mimic. (I don't think shared library is included yet but they might be in the future)

**Comment by aatchison** [comment]
I will have to try it, several things will have to change anyway

**Comment by forslund** [comment]
#67 resolved this. Closing.
