### ISSUE TITLE
Can I adjust sample rate?

### ISSUE THREAD

**Issue by helson73** [MycroftAI/mimic#78]
It seems that current sample rate is 8khz, 
Can I modify this to 16khz ?
Thanks.

**Comment by forslund** [comment]
Hi, I think this depends on the voice selected.

For example for kal (the default voice) I get
```
ake@babylon5:~/tmp/mimic-orig/build6$ ./mimic -voice kal -t "Hi there" hithere.wav
ake@babylon5:~/tmp/mimic-orig/build6$ file hithere.wav 
hithere.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 8000 Hz
```

for awb I get
```
ake@babylon5:~/tmp/mimic-orig/build6$ ./mimic -voice awb -t "Hi there" hithere.wav
ake@babylon5:~/tmp/mimic-orig/build6$ file hithere.wav 
hithere.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 16000 Hz
```

and alan pope's voice

```
ake@babylon5:~/tmp/mimic-orig/build6$ ./mimic -voice ../voices/mycroft_voice_4.0.flitevox -t "Hi there" hithere.wav
ake@babylon5:~/tmp/mimic-orig/build6$ file hithere.wav 
hithere.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 44100 Hz
```

The voice is selected using `-voice` followed by the voice of your choice. Either one of the precompiled voices (can be listed with `,/mimic -lv`) or a flitevox file (There are some in the */voices* directory)

**Comment by forslund** [comment]
@helson73 was the answer what you were looking for or did I misunderstand you?

**Comment by zeehio** [comment]
Each voice model can be trained with different sampling rates, so as @forslund correctly explained this is voice-dependant.

As there has been no feedback for 6 months and the question is answered, this issue can be closed
