### ISSUE TITLE
Warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]

### ISSUE THREAD

**Issue by DiogoSaraiva** [MycroftAI/mimic#90]
It have passed some hours from the `./dev_setup.sh` from 'mycroft-core' and when it reaches the part where works in 'mimic' i got tons of these warnings. In my raspberry pi 3 which is a single board computer, and with 4GB Swap, it finished compiling or something like that in about 2 hours or maybe less. And now in my AMD64 Mini Barebone PC (Giada A51B: AMD Dual-Core T56N, 4GB RAM, 128GB-SSD) is taking so much more and now i only see that warnings:

`Warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]`

My RPi3 has Raspbian with PIXEL (the lastest and updated)  
and my other PC has Linux Mint 18, updated with `apt-get upgrade`, etc...

Is that normal?  
Thanks

**Comment by forslund** [comment]
The warnings are to be expected, I know the build has been cleaned up quite heavily on the `development` branch and I don't see those warnings there.

I've seen that the build time varies a lot on different computers, the main culprit is the high quality voice of Alan Pope, which takes quite long time on it's own. I'm not sure what causes these widely different times, maybe there are some differing default settings for make (number of cores to use, etc) or an issue of available memory or task switching.

I will look into it.

**Comment by forslund** [comment]
Mimic builds without warnings now. The build time varies depending on architecture and I think we can't do much about it. Closing.

**Comment by vpzomtrrfrt** [comment]
I still see this error on the development branch:

```
src/lexicon/cst_lts.c: In function 'lts_apply':
src/lexicon/cst_lts.c:160:21: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  160 |         else if ((p = strchr(r->phone_table[phone], '-')) != NULL)
      |                     ^
cc1: all warnings being treated as errors
make[1]: *** [Makefile:3778: src/lexicon/libttsmimic_la-cst_lts.lo] Error 1
make[1]: Leaving directory '/home/colin/mimic1'
make: *** [Makefile:4809: all-recursive] Error 1
```
