### ISSUE TITLE
mycroft spanish lenguage

### ISSUE THREAD

**Issue by Manuelhck** [MycroftAI/mimic#93]
Is the work finished? Do you need any help Where can I find information?

**Comment by forslund** [comment]
Hi!

The work is sadly not finished. @zeehio has done the initial work in PR #86 adding a tokenizer for Spanish, he also outlines some areas where assistance is needed.

The big part after the tokenizer is obtaining a Spanish phonetic dictionary that can be included in the project. zeehio has started work on something called SAGA for handling multiple Spanish dialects that he might need help with.

If you feel like contributing I would also like a second opinion on PR #86, if there is an issue or not.

**Comment by forslund** [comment]
I'm closing this, so the discussion can continue in #3.
