### ISSUE TITLE
Ubuntu 16.04 cross to windows does not work as documented for earlier Ubuntu release

### ISSUE THREAD

**Issue by willauld** [MycroftAI/mimic#97]
It seems as if the required mingw32 and ming32-runtime packages are not available for 16.04. I installed mingw-w64 (no separate run-time) but this fails and I don't know what to try next. 

FYI - native compilers and runs ok. I assume that I can use a single file tree for both native and cross builds.

Thanks for any help.

**Comment by zeehio** [comment]
I'm on it. Quick fix (I'm testing it now):

Install `sudo apt-get install binutils-mingw-w64-i686 mingw-w64-i686-dev gcc-mingw-w64-i686 g++-mingw-w64-i686`

And on `run_testsuite.sh`, replace (two times):
`export HOST_TRIPLET="i586-mingw32msvc"`
with
`export HOST_TRIPLET="i686-w64-mingw32"`

Then build with: `./run_testsuite.sh winbuild`

**Comment by zeehio** [comment]
If it's not asking much, make sure you have a clean tree just in case `make distclean`

**Comment by willauld** [comment]
Thanks so much, 

 

I am trying it now and it seems to be moving forward. As I’m sure you know the build takes a long time. When it’s done and I can check the executable, I’ll let you know if it worked. 

 

Again, thanks!

Will

**Comment by willauld** [comment]
OK, got much further, including through some long compilers but stopped looking for mingw32-runtime.  Apt-get doesn't find it at all.

**Comment by willauld** [comment]
I commented out the part of the script that dealt with mingw32-runtime to see if the needed components may be supplied by another source in the 64 bit package. After doing this run_testsuite.sh runs almost to completion. It fails while attempting to run mimic:
 `
+ xvfb-run wine install/bin/mimic.exe -voice ap -t hello world hello_world_winbuild.wav
err:module:import_dll Loading library libportaudio-2.dll (which is needed by L"Z:\\home\\auld\\src\\github.com\\mimic\\install\\bin\\mimic.exe") failed (error c0000020).
err:module:LdrInitializeThunk Main exe initialization for L"Z:\\home\\auld\\src\\github.com\\mimic\\install\\bin\\mimic.exe" failed, status c0000135
+ exit 1
`
When I move mimic to a pc and try it (mimic -h) I also get an error message about libportaudio-2.dll:
`
C:\home\auld\temp\bin\libportaudio-2.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc000012f.
`
I don't know if this is because mingw32-runtime is missing but it is likely.

Also, xvfb needs to be added to the requirements list.

**Comment by zeehio** [comment]
My bet on the portaudio dll is that mingw-w64 has some weird issues with dashes in the dll name, but I am no expert and I have no time to debug that. I have used static linking to workaround that in the pull request on #98. To try it:

```
git checkout -b zeehio-crossbuild_xenial_windows development
git pull https://github.com/zeehio/mimic.git crossbuild_xenial_windows
```
```
NCORES=7 ./run_testsuite.sh winbuild
```
Think that each core will use 400MiB of RAM. On a system with 2 GiB of RAM I would not use more than 2 or 3 cores.

**Comment by willauld** [comment]
testing the fix. 

The first of the two git commands above didn't work for me. I dropped the development off the end and it worked. Will update when build is complete.

**Comment by willauld** [comment]
Mimic is fully building and working when moved to my windows 10 machine. Thanks for all the help with this issue!

**Comment by zeehio** [comment]
Closed via #98

**Comment by willauld** [comment]
I was just testing this update with a fresh clone and it doesn’t seem to work. It is still looking for a 32 bit compiler on Ubuntu 16.04. I diffed the branch that tested OK and this mainline run_testsuite.sh and there are lots of changes. The missing part for a 64bit compiler and static linking seems to be the two following diff extractions. Both the new are just setting the wrong compiler (and the first snippet looks like it’s not compiling statically as in the branch tested). 

 

Thanks,

Will

 

181,184c192,202

<     export HOST_TRIPLET="i586-mingw32msvc"

<     crosscompile_icu

<     crosscompile_portaudio

<     crosscompile_mimic --with-audio=portaudio

---

>     if [ `which i586-mingw32msvc-gcc` ]; then

>         export HOST_TRIPLET="i586-mingw32msvc"

>     elif [ `which i686-w64-mingw32-gcc` ]; then

>         export HOST_TRIPLET="i686-w64-mingw32"

>     else

>         echo "No windows cross-compiler found"

>         exit 1

>     fi

>     crosscompile_icu --disable-shared --enable-static

>     crosscompile_portaudio --disable-shared --enable-static

>     crosscompile_mimic  --disable-shared --enable-static --with-audio=portaudio

 

AND:

 

193c216,223

<     export HOST_TRIPLET="i586-mingw32msvc"

---

>     if [ `which i586-mingw32msvc-gcc` ]; then

>         export HOST_TRIPLET="i586-mingw32msvc"

>     elif [ `which i686-w64-mingw32-gcc` ]; then

>         export HOST_TRIPLET="i686-w64-mingw32"

>     else

>         echo "No windows cross-compiler found"

>         exit 1

>     fi

202c232,236

**Comment by forslund** [comment]
Hi Will,

are you testing master or the development branch? The PR was merged into
development.

(Master is updated for releases, development is continously updated)

Den 3 mar 2017 7:47 fm skrev "Will Auld" <notifications@github.com>:

**Comment by willauld** [comment]
I was testing master. Will switch to development and test it.

Thanks,

Will

**Comment by willauld** [comment]
Just tested the development branch: It works for me!

 

Thanks,

Will

 

From: Will Auld [mailto:will@auld.com] 
Sent: Thursday, March 02, 2017 4:46 PM
To: 'MycroftAI/mimic' <reply@reply.github.com>; 'MycroftAI/mimic' <mimic@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [MycroftAI/mimic] Ubuntu 16.04 cross to windows does not work as documented for earlier Ubuntu release (#97)

 

I was testing master. Will switch to development and test it.

Thanks,

Will
